apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets-store
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "C:/mycode/hackathon-02/phase-5/secrets.json"
  - name: nestedSeparator
    value: ":"